version: "3.9"
services:
  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
  matching-service:
    build: ./matching-service
    ports:
      - "8001:8001"
  collaboration-service:
    build: ./collaboration-service
    ports:
      - "8002:8002"
    depends_on:
      - redis
  redis:
    image: redis:alpine
  question-service:
    build: ./question-service
    ports:
      - "8003:8003"
  communication-service:
    build: ./communication-service
    ports:
      - "8004:8004"
